services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    restart: always
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: karwaan
      POSTGRES_PASSWORD: postgres123
    volumes:
      - karwaan_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "F90IMXyX_grAoGwJnZ-NJbcuPyoHBCTq"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: karwaan_test
      POSTGRES_PASSWORD: "y32LGbi2WUHqDYC-6S4TooAHSUlZlJkA"
    volumes:
      - karwaan_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "LbacJ7sY7z785RCmIurjbyui4IitqFj5"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  karwaan_data:
  karwaan_test_data:
