# This is the configuration file for your local development environment. By
# default, it runs a single server on port 8080. To set up your server, you will
# need to add the name of the database you are connecting to and the user name.
# The password for the database is stored in the config/passwords.yaml.
#
# When running your server locally, the server ports are the same as the public
# facing ports.

# Configuration for the main API server.
apiServer:
  port: 8080
  publicHost: 0.0.0.0
  publicPort: 8080
  publicScheme: http

# Configuration for the Insights server.
insightsServer:
  port: 8081
  publicHost: localhost
  publicPort: 8081
  publicScheme: http

# Configuration for the web server.
webServer:
  port: 8082
  publicHost: localhost
  publicPort: 8082
  publicScheme: http
  corsOriginRegex: 'http://localhost:[\d]*|http://10.226.253.89:[\d]*|http://192.168.\d+.\d+:[\d]*'

# This is the database setup for your server.
database:
  host: localhost
  port: 8090  # Changed from 8090 to 5432 (standard PostgreSQL port)
  name: karwaan
  user: postgres
  password: postgres123
  requireSsl: false
  isUnixSocket: false

# This is the setup for Redis.
redis:
  enabled: false
  host: localhost
  port: 8091

# Web server static files configuration - FIX THIS SECTION  
web:
  staticFiles:
    - path: /files/profile_pictures
      directoryPath: uploads/profile_pictures

maxRequestSize: 5242880 # Increased to 5MB for image uploads

sessionLogs:
  persistentEnabled: true
  consoleEnabled: true
  consoleLogFormat: text # Defaults to "json", options are "text" or "json"