# This is the configuration file for your production environment.
# Typically, you will want to route the traffic through a load balancer
# which adds SSL security through https. If you use Serverpod's standard
# Terraform scripts to deploy your server, all you need to change in
# this file is the examplepod.com domain name.

# Configuration for the main API server.
apiServer:
  port: 8080
  publicHost: api.examplepod.com
  publicPort: 443
  publicScheme: https

# Configuration for the Insights server.
insightsServer:
  port: 8081
  publicHost: insights.examplepod.com
  publicPort: 443
  publicScheme: https

# Configuration for the web server.
webServer:
  port: 8082
  publicHost: app.examplepod.com
  publicPort: 443
  publicScheme: https

# This is the database setup for your servers.
database:
  host: database.private-production.examplepod.com
  port: 5432
  name: serverpod
  user: postgres
  requireSsl: true

# This is the setup for Redis.
redis:
  enabled: false
  host: redis.private-production.examplepod.com
  port: 6379

# File storage configuration - FIX THIS SECTION
files:
  storage: local
  local:
    storages:
      public:
        path: ./uploads

# Web server static files configuration - FIX THIS SECTION
web:
  staticFiles:
    - path: /uploads
      directoryPath: uploads

maxRequestSize: 5242880 # Increased to 5MB for image uploads

sessionLogs:
  consoleEnabled: false

cors:
  allowOrigins:
    - 'http://localhost:5173'
    - 'http://127.0.0.1:5500'
    - 'http://localhost:5000'
    - 'https://karwaan-app.web.app'
    - 'https://your-domain.com'